apiVersion: v1
kind: Namespace
metadata:
  name: thinknyx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: thinknyx
  namespace: thinknyx
data:
  DB_URL: thinknyx.cpqrk0kuf9qo.us-east-2.rds.amazonaws.com:5432
  DB_USER: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: thinknyx
  namespace: thinknyx
type: Opaque
data: 
  DB_PWD: YWRtaW4xMjMK
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thinknyx
  namespace: thinknyx
  labels:
    app: sample-app
  annotations:
    git-repo: https://github.com/kul-samples/aws_rds_postgres.git
    tech: nodejs
    db_type: postgres
spec:
  template:
    metadata:
      labels: 
        app: sample-app
    spec:
      containers:
        - name: thinknyx
          image: kulbhushanmayer/sample-app:1.0
          envFrom:
            - configMapRef:
                name: thinknyx
            - secretRef:
                name: thinknyx
  replicas: 3
  selector:
    matchLabels:
      app: sample-app
  