service:
  port: 5432
  containerPort: 5432
  type: ClusterIP
  clusterIP: 10.99.12.13
replicaCount: 1
volumes:
  name: pgdata
  mountPath: /var/lib/postgresql/data
image:
  repository: postgres
  tag: 13.4

