apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tags.app }}"
        name: {{ .Chart.Name }}
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        envFrom:
        - secretRef:
            name: postgres
        - configMapRef:
            name: {{ .Chart.Name }}
        ports:
        - containerPort: {{ .Values.service.containerPort }}
          name: {{ .Chart.Name }}
      initContainers:
      - name: database-setup
        image: "{{ .Values.image.repository }}:{{ .Values.image.tags.init }}"
        command:
        - "sh"
        - "-c"
        - "sh database_setup.sh && sleep 30"
        envFrom:
        - configMapRef:
            name: {{ .Chart.Name }}
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: DB_PWD
