apiVersion: v1
kind: PersistentVolume
metadata:
  name: nodejs-app
spec:
  capacity:
    storage: 25Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /
    server: fs-74c8100f.efs.us-east-2.amazonaws.com
