apiVersion: v1
kind: Service
metadata:
  name: nodejs-app
spec:
  selector: # identify the pods based on the labels mentioned below and expose them for access
    name: nodejs-app
  clusterIP: "10.99.12.81"
  ports:
  - port: 80
    targetPort: nodejs-app
    nodePort: 30110
    name: nodejs-app
  type: NodePort
